using Pagos
using Test

include("aqua.jl")
include("api/staggered_grid.jl")
include("api/sigma_operators.jl")
include("api/runtime.jl")
include("api/state.jl")
include("api/sigma_gradients.jl")
include("api/boundary.jl")
include("api/advection.jl")
include("utils/indices.jl")
include("utils/integrators.jl")
include("numerics/differences.jl")
include("mechanics/stress.jl")
include("mechanics/drivingstress.jl")
include("mechanics/strainrate.jl")
include("mechanics/strainrate_staggered.jl")
include("topography/masks.jl")
include("mechanics/slab.jl")