name = "Pagos"
uuid = "c861e262-d8e9-4375-8e5f-146fb08f794b"
authors = ["Alexander Robinson", "Jan Swierczek-Jereczek"]
version = "0.0.1"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[compat]
FastGaussQuadrature = "1.0"
FillArrays = "1.11"
LinearAlgebra = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
