name = "Pagos"
uuid = "c861e262-d8e9-4375-8e5f-146fb08f794b"
version = "0.0.1"
authors = ["Alexander Robinson", "Jan Swierczek-Jereczek"]

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
PagosMakieExt = ["Makie"]

[compat]
DocStringExtensions = "0.9"
Downloads = "1.6"
FastGaussQuadrature = "1.0"
FillArrays = "1.11"
KernelAbstractions = "0.9"
LinearAlgebra = "1.10"
LinearSolve = "3.47"
SparseArrays = "1.11"
StatsBase = "0.34"
julia = "1.10"
